### ISSUE TITLE
python3.6 Example programs报错

### ISSUE THREAD

**Issue by akarrin** [chfw/pyecharts-snapshot#3]
运行Example programs报错“IndexError: list index out of range”

`IndexError                                Traceback (most recent call last)
<ipython-input-1-b09546c37749> in <module>()
     11 bar.add("商家B", attr, v2, is_stack=True)
     12 bar.render()
---> 13 make_a_snapshot('render.html', 'snapshot.png')

D:\ProgramData\lib\site-packages\pyecharts_snapshot\main.py in make_a_snapshot(file_name, output_name)
     53     else:
     54         content = io.TextIOWrapper(proc.stdout, encoding="utf-8").read()
---> 55     base64_imagedata = content.split(',')[1]
     56     imagedata = decode_base64(base64_imagedata.encode('utf-8'))
     57     if file_type == 'pdf':

IndexError: list index out of range`

**Comment by chfw** [comment]
Have you installed phantomjs? If yes, please try this command and see if you have any output:

    phantomjs pyechart_snapshot/phantomjs/snapshot.js render.html png

or you can download the js file from: 

https://github.com/chfw/pyecharts-snapshot/blob/master/pyecharts_snapshot/phantomjs/snapshot.js

and

**Comment by akarrin** [comment]
Thank you. You've helped me a lot.

**Comment by akarrin** [comment]
Thank you. You've helped me a lot.

**Comment by chfw** [comment]
My pleasure.
