### ISSUE TITLE
当pyecharts作line图时，会因html动画加载效果导致导出的png不全

### ISSUE THREAD

**Issue by akarrin** [chfw/pyecharts-snapshot#4]
在html文件加载完成后的效果：
![image](https://user-images.githubusercontent.com/31297624/29704862-22fa6930-89ae-11e7-9691-55ca318f3fda.png)
png文件：

![image](https://user-images.githubusercontent.com/31297624/29704802-dfeb5ef6-89ad-11e7-8244-09dabbf9c5bf.png)

**Comment by chfw** [comment]
I see. The snapshot was taken during the animation. Will find a good solution

**Comment by chfw** [comment]
Not sure how technical you are. If you are in an urgent need, you can modify '500' to '1000', or '10000'.

that means 0.5 s wait to 1s, or 10s.

https://github.com/chfw/pyecharts-snapshot/blob/master/pyecharts_snapshot/phantomjs/snapshot.js#L19

I will have a look by the end of today.

**Comment by akarrin** [comment]
Thank you，it has been solved using your method!!!

**Comment by chfw** [comment]
released. 0.0.6 is yours.
