### ISSUE TITLE
Windows html and snapshot filename path problems

### ISSUE THREAD

**Issue by dofine** [chfw/pyecharts-snapshot#5]
Windows 7 with Python 2.7, with the latest pyecharts and pyecharts-snapshot from github.
1. Using forward slash in path or any path generated with `os.path` module won't work. Change it to back slash works.
2. Chinses name in the full absolute file path won't work.

```python
radar.render("pics\\index.html")
make_a_snapshot("pics\\index.html", "pics\\echarts_radar3.png")
```

Result:

```
\lib\site-packages\pyecharts_snapshot\main.py", line 64, in make_a_snapshot
    base64_imagedata = content.split(',')[1]
IndexError: list index out of range
```

**Comment by chfw** [comment]
Do you have `phantomjs` installed?

**Comment by chfw** [comment]
Reproduced. Finally, I found a windows PC to reproduce it.

**Comment by chfw** [comment]
Please use version 0.0.8 for verification.
